[package]
name = "memcache_common"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+rust-shed@fb.com>']
license = "MIT OR Apache-2.0"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../README.md"

[lib]
path = "lib.rs"

[dependencies]
fbinit = { path = "../../fbinit", version = "0.1.0" }
anyhow = "1.0"
bytes = { version = "0.5", features = ["serde"] }
futures = "0.1.30"
