[package]
name = "time_ext"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+rust-shed@fb.com>']
license = "MIT OR Apache-2.0"
description = "Crate exxtending functionality of std::time"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../README.md"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
quickcheck = "0.9"
