load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("autocargo")

thrift_library(
    name = "just_knobs_struct",
    languages = [
        "rust",
    ],
    thrift_rust_options = "serde",
    thrift_srcs = {"just_knobs.thrift": None},
)
