[package]
name = "services"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+rust-shed@fb.com>']
license = "MIT OR Apache-2.0"
description = "Stubs for facebook services"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../README.md"

[dependencies]
fbinit = { path = "../fbinit", version = "0.1.0" }
services_common = { path = "common", version = "0.1.0" }
