load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbcode_macros//build_defs:rust_unittest.bzl", "rust_unittest")
load("@fbsource//tools/build_defs:glob_defs.bzl", "glob")

oncall("autocargo")

rust_library(
    name = "justknobs",
    srcs = glob(["src/*.rs"]),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "description": "Client for accessing JustKnobs. Noop crate for now",
            },
        },
    },
    named_deps = {
        "fb_justknobs": "//justknobs/rust:justknobs",
    },
    test_deps = [
        "fbsource//third-party/rust:maplit",
        "fbsource//third-party/rust:tokio",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/slog_glog_fmt:slog_glog_fmt",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:arc-swap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:slog",
        "fbsource//third-party/rust:tokio",
        "//common/rust/shed/cached_config:cached_config",
        "//common/rust/shed/justknobs_stub/cached_config_thrift_struct:just_knobs_struct-rust",
    ],
)

rust_unittest(
    name = "justknobs_in_unnitest",
    srcs = ["tests/justknobs_in_unittest.rs"],
    crate_root = "tests/justknobs_in_unittest.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:maplit",
        ":justknobs",
    ],
)
