[package]
name = "hostname"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
anyhow = "1.0"
hostname_orig = { package = "hostname", version = "0.3" }
